const fs = require('fs');
const path = require('path');

const apiBaseUrl = process.env.DREEM_API_BASE_URL || 'https://gateway.dreem.ai';
const accountsBaseUrl = process.env.DREEM_ACCOUNTS_API_BASE_URL || 'https://accounts.dreem.ai';

const content = `// Auto-generated by prebuild script — do not edit manually
export const API_BASE_URL = '${apiBaseUrl}';
export const ACCOUNTS_BASE_URL = '${accountsBaseUrl}';
`;

fs.writeFileSync(path.join(__dirname, '../nodes/Dreem/config.ts'), content);
console.log(`[generate-config] API_BASE_URL=${apiBaseUrl}, ACCOUNTS_BASE_URL=${accountsBaseUrl}`);
